In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

log = pd.read_csv("G:\data\datasets\logogo.csv")

In [2]:
log.head(10)

statusId accelerate      X      Y      Z
0         6          1 -0.268  0.536  9.785
1         6          1 -0.268  0.536  9.785
2         6          1 -0.268  0.536  9.785
3         6          1 -0.268  0.536  9.785
4         6          1 -0.268  0.536  9.785
5         6          1 -0.268  0.536  9.785
6         6          1 -0.268  0.536  9.785
7         6          1 -0.268  0.536  9.785
8         6          1 -0.268  0.536  9.785
9         6          1 -0.268  0.536  9.785

In [3]:
log.tail(10)

statusId accelerate      X      Y      Z
273552         8          1 -6.972  5.784  7.475
273553         8          1 -7.431  5.516  7.268
273554         8          1 -7.661  5.439  7.268
273555         8          1 -7.393  5.324  6.969
273556         8          1 -6.512  5.133  6.969
273557         8          1 -5.286  5.171  6.767
273558         8          1 -3.792  5.286  6.767
273559         8          1 -2.260  5.324  7.002
273560         8          1 -1.187  5.554  7.002
273561         8          1 -0.421  5.631  8.096

In [4]:
log.shape

(273562, 5)

In [7]:
x = log.drop('statusId', axis =1)
y = log['statusId']
z = x.drop('accelerate', axis = 1)

In [8]:
z.head(10)

X      Y      Z
0 -0.268  0.536  9.785
1 -0.268  0.536  9.785
2 -0.268  0.536  9.785
3 -0.268  0.536  9.785
4 -0.268  0.536  9.785
5 -0.268  0.536  9.785
6 -0.268  0.536  9.785
7 -0.268  0.536  9.785
8 -0.268  0.536  9.785
9 -0.268  0.536  9.785

In [9]:
from sklearn.model_selection import train_test_split
y_train, y_test, z_train, z_test = train_test_split(y,z, test_size = 0.2)

In [10]:
y_train.head(10)

7512      6
85982     6
25604     6
168500    7
95088     7
215262    8
88378     6
117635    7
91379     7
157029    7
Name: statusId, dtype: int64

In [13]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(z_train, y_train)

DecisionTreeClassifier()

In [14]:
y_pred = classifier.predict(z_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[18014     0     0]
 [    0 16773  1107]
 [    0  1214 17605]]
              precision    recall  f1-score   support

           6       1.00      1.00      1.00     18014
           7       0.93      0.94      0.94     17880
           8       0.94      0.94      0.94     18819

    accuracy                           0.96     54713
   macro avg       0.96      0.96      0.96     54713
weighted avg       0.96      0.96      0.96     54713

