In [20]:
import numpy as np 
from sklearn import preprocessing

In [21]:
Input_data = np.array(
[[2.1, -1.9, 5.5],
[-1.5, 2.4, 3.5],
[0.5, -7.9, 5.6],
[5.9, 2.3, -5.8]])

In [22]:
data_binarized = preprocessing.Binarizer(threshold=0.5).transform(Input_data)
print("\nBinarized data: \n", data_binarized)


Binarized data: 
 [[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


In [23]:
print("Mean: ", Input_data.mean(axis = 0))
print("Std Deviation: ", Input_data.std(axis = 0))

Mean:  [ 1.75  -1.275  2.2  ]
Std Deviation:  [2.71431391 4.20022321 4.69414529]


In [24]:
data_scaled = preprocessing.scale(Input_data)
print("Mean =", data_scaled.mean(axis = 0))
print("Std Deviation =", data_scaled.std(axis = 0))

Mean = [1.11022302e-16 0.00000000e+00 0.00000000e+00]
Std Deviation = [1. 1. 1.]


In [25]:
import pandas as pd 
log = pd.read_csv("G:\\data\\datasets\\logogo.csv")

In [26]:
log.head(10)


statusId  accelerate      X      Y      Z
0         6           1 -0.268  0.536  9.785
1         6           1 -0.268  0.536  9.785
2         6           1 -0.268  0.536  9.785
3         6           1 -0.268  0.536  9.785
4         6           1 -0.268  0.536  9.785
5         6           1 -0.268  0.536  9.785
6         6           1 -0.268  0.536  9.785
7         6           1 -0.268  0.536  9.785
8         6           1 -0.268  0.536  9.785
9         6           1 -0.268  0.536  9.785

In [27]:
log.tail(10)

statusId  accelerate      X      Y      Z
273551         8           1 -6.972  5.784  7.475
273552         8           1 -7.431  5.516  7.268
273553         8           1 -7.661  5.439  7.268
273554         8           1 -7.393  5.324  6.969
273555         8           1 -6.512  5.133  6.969
273556         8           1 -5.286  5.171  6.767
273557         8           1 -3.792  5.286  6.767
273558         8           1 -2.260  5.324  7.002
273559         8           1 -1.187  5.554  7.002
273560         8           1 -0.421  5.631  8.096

In [30]:
log_bin = preprocessing.Binarizer(threshold = 0.5).transform(log)
print('\nBinarized data: \n', log_bin)


Binarized data: 
 [[1. 1. 0. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 0. 1. 1.]
 ...
 [1. 1. 0. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 0. 1. 1.]]


In [31]:
print("Mean =", log.mean(axis = 0))
print("Std deviation =", log.std(axis = 0))

Mean = statusId      7.011562
accelerate    1.000000
X             0.137241
Y             0.086455
Z             7.073086
dtype: float64
Std deviation = statusId      0.818659
accelerate    0.000000
X             5.204382
Y             5.566247
Z             3.880858
dtype: float64


In [32]:
log_scale = preprocessing.scale(log)
print("Mean =", log_scale.mean(axis = 0))
print("std deviation =", log_scale.std(axis = 0))

Mean = [-3.49088297e-17  0.00000000e+00 -1.66232523e-17  3.65711550e-17
 -1.50232642e-16]
std deviation = [1. 0. 1. 1. 1.]


In [34]:
log_scale_min = preprocessing.MinMaxScaler(feature_range=(0, 1))
log_scaled_min = log_scale_min.fit_transform(log)
print('\nMin Max scaled data: \n', log_scaled_min)


Min Max scaled data: 
 [[0.         0.         0.50913074 0.52815463 0.83495146]
 [0.         0.         0.50913074 0.52815463 0.83495146]
 [0.         0.         0.50913074 0.52815463 0.83495146]
 ...
 [1.         0.         0.48652238 0.59853017 0.71644524]
 [1.         0.         0.49870047 0.60191078 0.71644524]
 [1.         0.         0.50739425 0.60304255 0.76303015]]


In [35]:
#data normalization 
log_norm = preprocessing.normalize(log, norm="l1")
print("\nL1 normalized data: \n", log_norm)


L1 normalized data: 
 [[ 0.34112229  0.05685372 -0.0152368   0.03047359  0.55631361]
 [ 0.34112229  0.05685372 -0.0152368   0.03047359  0.55631361]
 [ 0.34112229  0.05685372 -0.0152368   0.03047359  0.55631361]
 ...
 [ 0.33918426  0.04239803 -0.09581955  0.22572713  0.29687103]
 [ 0.35175658  0.04396957 -0.05219188  0.24420701  0.30787495]
 [ 0.34560221  0.04320028 -0.01818732  0.24326076  0.34974944]]


In [36]:
log_norm_2 = preprocessing.normalize(log, norm="l2")
print('\nL2 normalized data: ', log_norm_2)


L2 normalized data:  [[ 0.52006006  0.08667668 -0.02322935  0.0464587   0.84813128]
 [ 0.52006006  0.08667668 -0.02322935  0.0464587   0.84813128]
 [ 0.52006006  0.08667668 -0.02322935  0.0464587   0.84813128]
 ...
 [ 0.65875294  0.08234412 -0.18609771  0.43840008  0.57657351]
 [ 0.66144195  0.08268024 -0.09814145  0.45920608  0.57892707]
 [ 0.62770565  0.07846321 -0.03303301  0.44182632  0.63523812]]


In [41]:
#sample input labels
input_labels = ['red', 'black', 'red', 'green', 'black', 'yellow', 'white']
#creating a label encoder 
encoder = preprocessing.LabelEncoder()
encoder.fit(input_labels)

LabelEncoder()

In [42]:
#encoding a set of labels 
test_labels = ['green', 'red', 'black']
encoded_values = encoder.transform(test_labels)
print("\nLabels = ", test_labels)


Labels =  ['green', 'red', 'black']


In [43]:
print("Encoded values = ", list(encoded_values))

Encoded values =  [1, 2, 0]


In [45]:
#decoding a set of values 
encoded_values = [3, 0, 4, 1]
decoded_list = encoder.inverse_transform(encoded_values)
print('\nEncoded Values = ', encoded_values)
print('\nDecoded values = ', list(decoded_list))


Encoded Values =  [3, 0, 4, 1]

Decoded values =  ['white', 'black', 'yellow', 'green']
